name: Maintainer Onboarding
description: Onboarding checklist for maintainers
title: "Onboard <GitHub handle> as <SIG/WG FOO> maintainer"
labels: area/github-membership
body:
- type: markdown
  attributes:
    value: |
     This issue should be submitted by an existing maintainer of the affected SIG
- id: sig
  type: input
  attributes:
    label: "SIG name"
    placeholder: "SIG example"
  validations:
    required: true
- id: github_handle
  type: input
  attributes:
    label: "Github handle of the new maintainer"
    placeholder: "@example"
  validations:
    required: true
- id: checkboxes
  attributes:
    label: Requirements
    description: Before submitting 
    options:
      - label: Are you (submitter of this issue) a maintainer of the affected SIG?
        required: true
      - label: Is this maintainer a member of the OpenTelemetry GitHub organization already?
        required: true
