name: Maintainer Onboarding
description: Onboarding checklist for maintainers
title: "Onboard <GitHub handle> as <SIG/WG FOO> maintainer"
labels: area/github-membership
body:
- id: sig
  type: input
  attributes:
    label: "SIG name"
    placeholder: "SIG example"
  required: true
- id: github_handle
  type: input
  attributes:
    label: "Github handle of the new maintainer"
    placeholder: "@example"  
  required: true
